- include_vars: ../../../config.yaml
- include: set-hostname.yaml
- include: register-rhn.yaml
- include: create-stack-user.yaml 
- include: create-dirs.yaml
- include: modify-hosts.yaml
- include: update-repos.yaml
- include: update-system.yaml
- include: reboot-system.yaml
- include: install-rdo.yaml
- include: bootif-fix.yaml

